export const CHANGE_MUSIC_LIST = 'CHANGE_MUSIC_LIST';

export const CHANGE_STATE = 'CHANGE_STATE';

export const CHANGE_CURRENT_TIME = 'CHANGE_CURRENT_TIME';

export const CHANGE_CURRENT_SONG = 'CHANGE_CURRENT_SONG';

export const CHANGE_CURRENT_DURATION = 'CHANGE_CURRENT_DURATION';

export const CHANGE_VOLUME = 'CHANGE_VOLUME';
